<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="steer_radius" value="0.03" /> <!-- Link 1 -->
  <xacro:property name="steer_effort"   value="10.0"/>
  <xacro:property name="steer_velocity" value="5.0"/>

  <macro name="front_wheel" params="name parent radius thickness length width axel_offset right_left steer_height ">
    <link name="${name}_steer_link">
      <inertial>
        <origin xyz="0 0 0.4" rpy="0 0 0"/>
        <mass value="1"/>
        <inertia ixx="0.2" ixy="0" ixz="0" iyy="0.2" iyz="0" izz="0.2"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0.2" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${steer_radius}" length="${steer_height}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0.2" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${steer_radius}" length="${steer_height}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${name}_steer_joint" type="revolute">
      <parent link="${parent}_link"/>
      <child link="${name}_steer_link"/>
      <origin xyz="${length/2-axel_offset} ${right_left*(width/2-axel_offset)} ${-steer_height}" rpy="0 0 0"/>
      <!--insert_block name="origin"/-->
      <axis xyz="0 0 1"/>
      <limit effort="${steer_effort}"
             lower="${-180.0 * deg_to_rad}" upper="${180.0 * deg_to_rad}"
             velocity="${steer_velocity}"/>
     </joint>

    <gazebo reference="${name}_steer_link">
      <material>Gazebo/WoodFloor</material>
    </gazebo>
    <gazebo reference="${name}_wheel_link">
      <material>Gazebo/WoodFloor</material>
    </gazebo>
  </macro>

  <macro name="rear_wheel" params="name parent radius thickness length width axel_offset right_left steer_height ">
    <link name="${name}_steer_link">
      <inertial>
        <origin xyz="0 0 0.4" rpy="0 0 0"/>
        <mass value="1"/>
        <inertia ixx="0.2" ixy="0" ixz="0" iyy="0.2" iyz="0" izz="0.2"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0.2" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${steer_radius}" length="${steer_height}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0.2" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${steer_radius}" length="${steer_height}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${name}_steer_joint" type="revolute">
      <parent link="${parent}_link"/>
      <child link="${name}_steer_link"/>
      <origin xyz="${-(length/2-axel_offset)} ${right_left*(width/2-axel_offset)} ${-steer_height}" rpy="0 0 0"/>
      <!--insert_block name="origin"/-->
      <axis xyz="0 0 1"/>
      <limit effort="${steer_effort}"
             lower="${-180.0 * deg_to_rad}" upper="${180.0 * deg_to_rad}"
             velocity="${steer_velocity}"/>
     </joint>

    <gazebo reference="${name}_steer_link">
      <material>Gazebo/WoodFloor</material>
    </gazebo>

  </macro>


  <!--macro name="rear_wheel" params="name parent radius thickness *origin">
    <link name="${name}_wheel_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1"/>
        <inertia ixx="0.2" ixy="0" ixz="0" iyy="0.2" iyz="0" izz="0.2"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${thickness}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${thickness}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${name}_wheel_joint" type="continuous">
      <parent link="${parent}_link"/>
      <child link="${name}_wheel_link"/>
      <insert_block name="origin"/>
      <axis xyz="0 0 1"/>
    </joint>

    <transmission name="${name}_wheel_joint_trans" type="SimpleTransmission">
      <actuator name="${name}_wheel_joint_motor"/>
      <joint name="${name}_wheel_joint"/>
      <mechanicalReduction>1</mechanicalReduction>
      <motorTorqueConstant>1</motorTorqueConstant>
    </transmission>

    <gazebo reference="${name}_wheel_link">
      <material>Gazebo/Red</material>
    </gazebo>
  </macro-->
</robot>
